#!/bin/bash
#set -x
source config.sh

for I in $(seq $NET_START $NET_END)
do
  echo -n "s4_$I: "
  STATS=$(cgminer-api stats ${BASE_NET}.$I | grep "GHS 5s\]")
  if [ "$?" -eq "0" ]; then
    HASHRATE=$(echo $STATS | cut -f4 -d' ' | cut -f1 -d".")
    if [ "$HASHRATE" -eq "0" ]; then
      echo -n "Hasrate 5s reporting 0. "
      if [ "$REBOOT" == "yes" ]; then
        RES=$(sshpass -p admin ssh -oStrictHostKeyChecking=no -l root ${BASE_NET}.$I /sbin/reboot >&2 2> /dev/null)
        if [ "$?" -eq "0" ]; then
            echo Rebooting.
        else
          echo Error trying to reboot miner.
        fi
      else
        echo ""
      fi
    else
      echo OK
    fi
  else
    echo Offline
  fi
done


