#!/bin/bash
source config.sh

for I in $(seq $NET_START $NET_END)
do
  echo -n "$I: "
  RES=$(cgminer-api stats ${BASE_NET}.$I | grep  '\[chain_acs')
  if [ "$?" -eq "0" ]; then

    echo $RES  | grep -o 'x' | wc -l
  else
    echo Offline
  fi
done

