#!/bin/bash
source config.sh

for I in $(seq $NET_START $NET_END)
do
  echo -n "$I: "
  RES=$(sshpass -p admin ssh -oStrictHostKeyChecking=no -l root ${BASE_NET}.$I /sbin/reboot >&2 2> /dev/null)
  if [ "$?" -eq "0" ]; then
    echo Rebooting
  else
    echo Error
  fi
done

